---
ruby_library_version:   "1.9.1"
ruby_version:           "ruby-1.9.3-p484"
ruby_checksum:          "0fdc6e860d0023ba7b94c7a0cf1f7d32908b65b526246de9dfd5bb39d0d7922b"
ruby_download_location: "http://cache.ruby-lang.org/pub/ruby/1.9/{{ ruby_version }}.tar.bz2"
