
---
# Database playbook
- name: Database
  user: ubuntu
  sudo: True
  tags: database
  hosts: all
  roles:
    - base
    - ruby-1.9.3
    - nerve
    - postgres
  vars_files:
    - vars/{{ ansible_distribution }}.yml
