
---
# Webserver playbook
- name: Webserver
  user: ubuntu
  sudo: True
  tags: webserver
  hosts: all
  roles:
    - base
    - ruby-1.9.3
    - synapse
    - webserver
  vars_files:
    - vars/{{ ansible_distribution }}.yml
